// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_choosehouse.cpp"
#include "EWIEGA46WW/moc_creategamewindow.cpp"
#include "EWIEGA46WW/moc_joingamewindow.cpp"
#include "EWIEGA46WW/moc_maingame.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_waitingWindow.cpp"
